name: ntier

services:
  adminer: # 1st service
    image: adminer
    ports: 
      - port: 8080
        expose: true
    route: # trait
      domain: ntier.apps.v95.io
      http:
        "/": 8080
  backend: # 2nd service
    image: postgres
    ports:
      - port: 5432
        expose: true